### ISSUE TITLE
Scale image

### ISSUE THREAD

**Issue by coyksdev** [kherel/pixel_perfect#1]
Hi, 

My mockup image size 375 X 812.  How can I scale the image to fit the screen on any devices?

**Comment by kherel** [comment]
Technically you can stretch your image like that...
```
PixelPerfect.extended(
  image: Image.asset(
    'assets/element.png',
    scale: 2,
    width: MediaQuery.of(context).size.width,
    fit: BoxFit.fill,
  ), 
  .. 
)
```

but I recommend you to not to do it, instead of it create simulator for phone with the same screen size, for example many of iPhones have this size...

I'm closing the issue, but we can continue our dialog here.

**Comment by apoorvpandey0** [comment]
But we should add the scaling feature in the plugin in future right?
I was testing it on chrome and wanted to design the UI for my phone, but the image was not scalable.
I'd say that we should maintain the image aspect ratio and just give an option to scale.

**Comment by kherel** [comment]
Sure, it's already there..

```
return PixelPerfect(
  assetPath: 'assets/design.png', // path to your asset image
  scale: 1 // scale value (optional)
  ..
  )
)
```
