### ISSUE TITLE
Responsive layout

### ISSUE THREAD

**Issue by imSaharukh** [kherel/pixel_perfect#2]
does this package will create a responsive UI? or I have to do some extra work?

**Comment by kherel** [comment]
https://github.com/kherel/pixel_perfect/issues/1

**Comment by imSaharukh** [comment]
@kherel why did u close this issue brother?

**Comment by kherel** [comment]
The purpose of this package is to help compare exported image and your layout.

So export an image in the same resolution as your emulator.

**Comment by imSaharukh** [comment]
but it would be great if it become responsive as well.

you can take this as a feature request

**Comment by kherel** [comment]
I'll think about it. 
I'm closing for now your issue. But If you have other questions or ideas feel free to leave comments below.
