### ISSUE TITLE
PRs open?

### ISSUE THREAD

**Issue by roipeker** [kherel/pixel_perfect#3]
Hi there. Are PRs opens for contribution?

Today I was about to start a similar idea, until i found this one on pubdev... 

I made a few tweaks to reset move position, constrain dragging in the screen area, and  blendMode support, which was my main need...

 So, let me know if you are interested in PRs, or I should go with my own version.

Have a great weekend.

**Comment by kherel** [comment]
sure.. feel free to make a merge request. PRs welcome! :)
