### ISSUE TITLE
The getter 'accentColor' isn't defined for the class 'ThemeData'.

### ISSUE THREAD

**Issue by konin-sergei** [kherel/pixel_perfect#5]
Hello!
When i try to run examle:
Error (Xcode): ../lib/src/pixel_perfect.dart:142:62: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
Could not build the application for the simulator.
Error launching application on iPhone 14.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources
• No issues found!

**Comment by kherel** [comment]
thanks man.

**Comment by kherel** [comment]
fixed in https://github.com/kherel/pixel_perfect/commit/e9f2758a4252dd7b5fee52aa9a90198a2ad302bd
